
import os

content = """# Generated by Django on 2025-12-10 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spme_monitoreo', '0006_fix_missing_fields'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE spme_monitoreo_solicitudpagodirecto DROP COLUMN nombre, DROP COLUMN paterno, DROP COLUMN materno, DROP COLUMN ci, DROP COLUMN banco, DROP COLUMN numeroCuenta, DROP COLUMN cargo;",
            reverse_sql=""
        ),
    ]
"""

path = r"d:\proyecto_smpe\spme\spme_monitoreo\migrations\0007_remove_extra_columns.py"
with open(path, "w", encoding='utf-8') as f:
    f.write(content)
print("Migration 0007 file patched.")
