
import os

content = """# Generated by Django 5.2 on 2025-12-10 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spme_monitoreo', '0004_remove_solicitudfondos_responsable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='solicitudpagodirecto',
        #     old_name='bloquearIconos',
        #     new_name='bloquearIconosSolFondos',
        # ),
        # migrations.RemoveField(
        #     model_name='solicitudpagodirecto',
        #     name='fecha_realizacion',
        # ),
        # migrations.RemoveField(
        #     model_name='solicitudpagodirecto',
        #     name='fuente_financiamiento',
        # ),
        migrations.RemoveField(
            model_name='solicitudpagodirecto',
            name='responsable',
        ),
        migrations.AddField(
            model_name='solicitudpagodirecto',
            name='contador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_contador_sol_pago_directo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudpagodirecto',
            name='datos_forma_pago',
            field=models.JSONField(blank=True, null=True, verbose_name='Datos de forma de pago'),
        ),
        migrations.AddField(
            model_name='solicitudpagodirecto',
            name='fechaRealizacionActividad',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de realizacion del actividad'),
        ),
        migrations.AlterField(
            model_name='solicitudpagodirecto',
            name='lugarSolicitud',
            field=models.TextField(blank=True, null=True),
        ),
    ]
"""

path = r"d:\proyecto_smpe\spme\spme_monitoreo\migrations\0005_rename_bloqueariconos_solicitudpagodirecto_bloqueariconossolfondos_and_more.py"
with open(path, "w") as f:
    f.write(content)
print("Migration file patched.")
