
import os

content = """# Generated by Django on 2025-12-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spme_monitoreo', '0005_rename_bloqueariconos_solicitudpagodirecto_bloqueariconossolfondos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpagodirecto',
            name='descripcion_actividad',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la actividad'),
        ),
        migrations.AddField(
            model_name='solicitudpagodirecto',
            name='objetivo_actividad',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivo de la actividad'),
        ),
    ]
"""

path = r"d:\proyecto_smpe\spme\spme_monitoreo\migrations\0006_fix_missing_fields.py"
with open(path, "w", encoding='utf-8') as f:
    f.write(content)
print("Migration 0006 file patched.")
