# Generated by Django 5.2 on 2025-05-31 21:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('redaccion', models.CharField(choices=[('GUIA', 'Indicador GUIA'), ('SMART', 'Indicador SMART')], max_length=5)),
                ('fuente_verificacion', models.TextField()),
                ('target_poblacion', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('A-Z', 'Literal'), ('1-9', 'Numerico'), ('%', 'Porcentual')], default='A-Z', max_length=5)),
                ('baseline', models.CharField(blank=True, max_length=10, null=True)),
                ('target_q1', models.CharField(blank=True, max_length=10, null=True)),
                ('target_q2', models.CharField(blank=True, max_length=10, null=True)),
                ('target_q3', models.CharField(blank=True, max_length=10, null=True)),
                ('target_q4', models.CharField(blank=True, max_length=10, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Indicador de Proyecto',
                'verbose_name_plural': 'Indicadores de Proyecto',
            },
        ),
        migrations.CreateModel(
            name='IndicadorPeiBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('descripcion', models.TextField(verbose_name='Indicador')),
                ('captura_informacion', models.TextField(blank=True, null=True)),
                ('responsabilidad', models.CharField(blank=True, max_length=255, null=True)),
                ('frecuencia_recopilacion', models.CharField(blank=True, max_length=255, null=True)),
                ('uso_informacion', models.TextField(blank=True, null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('modificado_el', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Indicador PEI',
                'verbose_name_plural': 'Indicadores PEI',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='InstanciaGestora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('clasificador', models.CharField(blank=True, max_length=5, null=True)),
                ('instancia', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Instancia Gestora',
                'verbose_name_plural': 'Instancias Gestoras',
                'ordering': ['-codigo'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoGeneralProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('supuestos', models.TextField(blank=True)),
                ('riesgos', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Objetivo General del Proyecto',
                'verbose_name_plural': 'Objetivos Generales del Proyecto',
            },
        ),
        migrations.CreateModel(
            name='ObjetivoPei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('modificado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Objetivo General PEI',
                'verbose_name_plural': 'Objetivos Generales PEI',
            },
        ),
        migrations.CreateModel(
            name='Pei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fecha_fin', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('esta_vigente', models.BooleanField(default=False)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('modificado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PEI',
                'verbose_name_plural': 'PEIs',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
            },
        ),
        migrations.CreateModel(
            name='ProductoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=150)),
                ('supuestos', models.TextField(blank=True, null=True)),
                ('riesgos', models.TextField(blank=True, null=True)),
                ('entregado', models.BooleanField(default=False)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Producto del Proyecto',
                'verbose_name_plural': 'Productos del Proyecto',
            },
        ),
        migrations.CreateModel(
            name='ResultadoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('supuestos', models.TextField(blank=True)),
                ('riesgos', models.TextField(blank=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Resultado de Proyecto',
                'verbose_name_plural': 'Resultados de Proyecto',
            },
        ),
        migrations.CreateModel(
            name='IndicadorPeiCualitativo',
            fields=[
                ('indicadorpeibase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spme_estructuracion.indicadorpeibase')),
                ('tipo', models.CharField(default='Avance', editable=False, max_length=20, verbose_name='Tipo')),
                ('umbral_des_literal_um1', models.TextField(blank=True, null=True)),
                ('umbral_des_literal_um2', models.TextField(blank=True, null=True)),
                ('umbral_des_literal_um3', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Indicador Cualitativo PEI',
                'verbose_name_plural': 'Indicadores Cualitativos PEI',
            },
            bases=('spme_estructuracion.indicadorpeibase',),
        ),
        migrations.CreateModel(
            name='IndicadorPeiCuantitativo',
            fields=[
                ('indicadorpeibase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spme_estructuracion.indicadorpeibase')),
                ('tipo', models.CharField(default='Proporcion', editable=False, max_length=20, verbose_name='Tipo')),
                ('numerador', models.TextField(blank=True, null=True)),
                ('denominador', models.TextField(blank=True, null=True)),
                ('umbral_des_numeral', models.IntegerField(blank=True, null=True)),
                ('umbral_des_literal_um1', models.TextField(blank=True, null=True)),
                ('umbral_des_literal_um2', models.TextField(blank=True, null=True)),
                ('umbral_des_literal_um3', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Indicador Cuantitativo PEI',
                'verbose_name_plural': 'Indicadores Cuantitativos PEI',
            },
            bases=('spme_estructuracion.indicadorpeibase',),
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.TextField(verbose_name='Redaccion del KPI')),
                ('objetivo_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='spme_estructuracion.objetivogeneralproyecto', verbose_name='Objetivo General Asociado')),
            ],
        ),
        migrations.AddField(
            model_name='indicadorpeibase',
            name='objetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicador_pei_objetivo', to='spme_estructuracion.objetivopei'),
        ),
        migrations.AddField(
            model_name='objetivopei',
            name='pei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pei_obj_general', to='spme_estructuracion.pei'),
        ),
        migrations.CreateModel(
            name='ProductoResultadoOE',
            fields=[
                ('productoproyecto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spme_estructuracion.productoproyecto')),
            ],
            options={
                'verbose_name': 'Producto del Resultado Objetivo Especifico',
                'verbose_name_plural': 'Productos del Resultado Objetivo Especifico',
            },
            bases=('spme_estructuracion.productoproyecto',),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estado', models.CharField(choices=[('ES', 'Estructuracion'), ('EP', 'En Planificacion')], default='ES', max_length=2)),
                ('creado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('instancia_gestora', models.ManyToManyField(related_name='proyectos', to='spme_estructuracion.instanciagestora')),
                ('pei', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='spme_estructuracion.pei', verbose_name='PEI asociado')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='objetivogeneralproyecto',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='objetivo_general', to='spme_estructuracion.proyecto', verbose_name='Proyecto asociado'),
        ),
        migrations.CreateModel(
            name='ObjetivoEspecificoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('supuestos', models.TextField(blank=True, null=True)),
                ('riesgos', models.TextField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_especificos', to='spme_estructuracion.proyecto', verbose_name='Proyecto asociado')),
            ],
            options={
                'verbose_name': 'Objetivo Especifico del Proyecto',
                'verbose_name_plural': 'Objetivos Especificos del Proyecto',
            },
        ),
        migrations.CreateModel(
            name='IndicadorObjetivoEspecifico',
            fields=[
                ('indicadorproyecto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spme_estructuracion.indicadorproyecto')),
                ('objetivo_especifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicador_oe', to='spme_estructuracion.objetivoespecificoproyecto')),
            ],
            options={
                'verbose_name': 'Indicador Objetivo Especifico de Proyecto',
                'verbose_name_plural': 'Indicadores Resultado Objetivo General de Proyecto',
            },
            bases=('spme_estructuracion.indicadorproyecto',),
        ),
        migrations.CreateModel(
            name='IndicadorObjetivoGeneral',
            fields=[
                ('indicadorproyecto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spme_estructuracion.indicadorproyecto')),
                ('objetivo_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicador_og', to='spme_estructuracion.objetivogeneralproyecto')),
            ],
            options={
                'verbose_name': 'Indicador Objetivo General de Proyecto',
                'verbose_name_plural': 'Indicadores Objetivo General de Proyecto',
            },
            bases=('spme_estructuracion.indicadorproyecto',),
        ),
        migrations.CreateModel(
            name='ProductoOE',
            fields=[
                ('productoproyecto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spme_estructuracion.productoproyecto')),
                ('proceso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto_oe', to='spme_estructuracion.proceso')),
            ],
            options={
                'verbose_name': 'Producto Objetivo Especifico',
                'verbose_name_plural': 'Productos Objetivos Especificos',
            },
            bases=('spme_estructuracion.productoproyecto',),
        ),
        migrations.CreateModel(
            name='ResultadoOE',
            fields=[
                ('resultadoproyecto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spme_estructuracion.resultadoproyecto')),
                ('proceso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultado_oe', to='spme_estructuracion.proceso')),
            ],
            options={
                'verbose_name': 'Resultado Objetivo Especifico',
                'verbose_name_plural': 'Resultados Objetivo Especifico',
            },
            bases=('spme_estructuracion.resultadoproyecto',),
        ),
        migrations.CreateModel(
            name='IndicadorResultadoObjEspecifico',
            fields=[
                ('indicadorproyecto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spme_estructuracion.indicadorproyecto')),
                ('resultado_obj_especifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicador_res_oe', to='spme_estructuracion.resultadooe')),
            ],
            options={
                'verbose_name': 'Indicador Resultado de Objetivo Especifico',
                'verbose_name_plural': 'Indicadores Resultado Objetivo Especifico',
            },
            bases=('spme_estructuracion.indicadorproyecto',),
        ),
        migrations.CreateModel(
            name='ResultadoOG',
            fields=[
                ('resultadoproyecto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spme_estructuracion.resultadoproyecto')),
                ('proceso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultado_og', to='spme_estructuracion.proceso')),
            ],
            options={
                'verbose_name': 'Resultado Objetivo General',
                'verbose_name_plural': 'Resultados Objetivo General',
            },
            bases=('spme_estructuracion.resultadoproyecto',),
        ),
        migrations.CreateModel(
            name='IndicadorResultadoObjGral',
            fields=[
                ('indicadorproyecto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spme_estructuracion.indicadorproyecto')),
                ('resultado_og', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicador_res_og', to='spme_estructuracion.resultadoog')),
            ],
            options={
                'verbose_name': 'Indicador Resultado Objetivo General de Proyecto',
                'verbose_name_plural': 'Indicadores Resultado Objetivo General de Proyecto',
            },
            bases=('spme_estructuracion.indicadorproyecto',),
        ),
    ]
